---
title: "Hasta-Nada Mas Analysis"
output:
  pdf_document: 
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```






# RESULTS

```{r, include=FALSE}
library(lme4)
#hast  <- read.csv("V4.csv")
hast  <- read.csv("https://raw.githubusercontent.com/umontano/kar/master/hasta_nada_mas.csv")

#CHANGE LEVELS NAMES (IN OODER TO CHANGE THE ORDER IN REGRESSIONS)
#hast$MD  <- relevel(hast$MD, "s") 
hast$Imagen  <- factor(hast$Imagen, levels = c("d1", "d2", "t", "c"))
hast$MD  <- factor(hast$MD, levels = c("s", "n", "h"))

```



## Generating Models
```{r}

mixed3 <- lmer(Tiempo ~ 1 + MD + Imagen +  MD : Imagen  + (1 | Nombre) + (1 | Edad) + (1 | Sexo) , data=hast)
mixed2 <- lmer(Tiempo ~ 1 + MD + Imagen +  MD : Imagen  + (1 | Nombre) + (1 | Edad) , data=hast)
mixed1 <- lmer(Tiempo ~ 1 + MD + Imagen +  MD:Imagen  + (1 | Nombre) , data=hast)
linear <- glm(Tiempo ~ 1 + MD + Imagen +  MD : Imagen , family = gaussian, data=hast, model=FALSE, x=FALSE, y=FALSE)

save(mixed3, file = "mixed3.Rdata")
save(mixed2, file = "mixed2.Rdata")
save(mixed1, file = "mixed1.Rdata")
save(linear, file = "linear.Rdata")

```

# Evaluating Models
Results show that the best model is the lineat model
```{r}
AIC(logLik(linear))
AIC(logLik(mixed1))
AIC(logLik(mixed2))
AIC(logLik(mixed3))
```


## Mixed Effects Models Evaluation
Results show that the best models is the one with only one random effect


```{r}
anova(mixed1,  mixed2,  mixed3, test = "Chisq", refit = F)
```


# Mixed Effects Model

```{r}
summary(mixed1)
```


## P-VALUES
```{r}
anova(mixed1)
```


#  Equivalent ANOVA with post-hoc

```{r}
#resultsanova <- aov(Tiempo ~ 1 + MD + Imagen +  MD : Imagen,  data=hast)
#summary(resultsanova)
#TukeyHSD(resultsanova)

```


```{r}
#https://raw.githubusercontent.com/umontano/kar/master/ceguera_mafer.csv
library(ggplot2)
library(ggbeeswarm)
#ceg  <- read.csv( "https://raw.githubusercontent.com/umontano/kar/master/ceguera_mafer.csv")
ceg  <- read.csv( "https://raw.githubusercontent.com/umontano/kar/master/cegu.csv")
plot(ceg$Atencion_foc, ceg$Calificacion)

ggplot(ceg, aes(Atencion_foc, Calificacion
#                , col=as.factor(Sexo)
                )) +
        geom_jitter(alpha=0.5) +
        geom_smooth(method = "lm", se = T, fullrange = T)

ggplot(ceg, aes(Sexo, Calificacion
                )) +
        geom_beeswarm(alpha=0.6) +
        geom_smooth(method = "lm", se = T, fullrange = T)

```
